import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { auth } from '@/auth'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Login App',
  description: 'Generated by Mohk',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    // we use session Provider in the layout since it's needed by useSession()
    <SessionProvider session={session}>
<html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </SessionProvider>
    
  )
}
